services:
  chrome:
    ports:
      - "5300:3000"

  mangashelf.db:
    ports:
      - "3303:3306"

  mangashelf:
    build:
      context: .
      dockerfile: MangaShelf/Dockerfile
    ports:
      - "5299:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MANGASHELF_WEBROOT_PATH: /app/wwwroot

  mangashelf.parser:
    build:
      context: .
      dockerfile: MangaShelf.Parser/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      MANGASHELF_WEBROOT_PATH: /app/wwwroot

  mangashelf.migration:
    build:
      context: .
      dockerfile: MangaShelf.Migration/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      MANGASHELF_WEBROOT_PATH: /app/wwwroot