//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaShelf.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterfaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaShelf.Localization.Resources.UserInterfaceResource", typeof(UserInterfaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to library.
        /// </summary>
        public static string AddToLibrary {
            get {
                return ResourceManager.GetString("AddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days till release.
        /// </summary>
        public static string DaysTillRelease {
            get {
                return ResourceManager.GetString("DaysTillRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding reading.
        /// </summary>
        public static string ErrorAddingReading {
            get {
                return ResourceManager.GetString("ErrorAddingReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading ownership.
        /// </summary>
        public static string ErrorLoadingOwnership {
            get {
                return ResourceManager.GetString("ErrorLoadingOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading reading.
        /// </summary>
        public static string ErrorLoadingReading {
            get {
                return ResourceManager.GetString("ErrorLoadingReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} days.
        /// </summary>
        public static string FewDays {
            get {
                return ResourceManager.GetString("FewDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder.
        /// </summary>
        public static string ItsPreorder {
            get {
                return ResourceManager.GetString("ItsPreorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewManga.
        /// </summary>
        public static string NewManga {
            get {
                return ResourceManager.GetString("NewManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPreorders.
        /// </summary>
        public static string NewPreorders {
            get {
                return ResourceManager.GetString("NewPreorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found for the selected date range..
        /// </summary>
        public static string No_updates_found_for_the_selected_date_range_ {
            get {
                return ResourceManager.GetString("No updates found for the selected date range.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        public static string NoDescrption {
            get {
                return ResourceManager.GetString("NoDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news.
        /// </summary>
        public static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preorders.
        /// </summary>
        public static string NoPreorders {
            get {
                return ResourceManager.GetString("NoPreorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoReviews.
        /// </summary>
        public static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        public static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder.
        /// </summary>
        public static string Preorder {
            get {
                return ResourceManager.GetString("Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder arrived.
        /// </summary>
        public static string PreorderArrived {
            get {
                return ResourceManager.GetString("PreorderArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder date.
        /// </summary>
        public static string PreorderDate {
            get {
                return ResourceManager.GetString("PreorderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string PreorderIsDue {
            get {
                return ResourceManager.GetString("PreorderIsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorders.
        /// </summary>
        public static string Preorders {
            get {
                return ResourceManager.GetString("Preorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results per page.
        /// </summary>
        public static string ResultPerPage {
            get {
                return ResourceManager.GetString("ResultPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisIsPreorderVolume.
        /// </summary>
        public static string ThisIsPreorderVolume {
            get {
                return ResourceManager.GetString("ThisIsPreorderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
