//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaShelf.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInterfaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaShelf.Localization.Resources.UserInterfaceResource", typeof(UserInterfaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Add to library.
        /// </summary>
        public static string AddToLibrary {
            get {
                return ResourceManager.GetString("AddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to AdminVolumes.
        /// </summary>
        public static string AdminVolumes {
            get {
                return ResourceManager.GetString("AdminVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to AgeRestriction.
        /// </summary>
        public static string AgeRestriction {
            get {
                return ResourceManager.GetString("AgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ApplyCrop.
        /// </summary>
        public static string ApplyCrop {
            get {
                return ResourceManager.GetString("ApplyCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to AutoCrop.
        /// </summary>
        public static string AutoCrop {
            get {
                return ResourceManager.GetString("AutoCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to BackToList.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ChangesSaved.
        /// </summary>
        public static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to CoverImage.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to CroppedCover.
        /// </summary>
        public static string CroppedCover {
            get {
                return ResourceManager.GetString("CroppedCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to CropSize.
        /// </summary>
        public static string CropSize {
            get {
                return ResourceManager.GetString("CropSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to CropSuccessful.
        /// </summary>
        public static string CropSuccessful {
            get {
                return ResourceManager.GetString("CropSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to CurrentCroppedVersion.
        /// </summary>
        public static string CurrentCroppedVersion {
            get {
                return ResourceManager.GetString("CurrentCroppedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to {count} days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Days till release.
        /// </summary>
        public static string DaysTillRelease {
            get {
                return ResourceManager.GetString("DaysTillRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to EditVolume.
        /// </summary>
        public static string EditVolume {
            get {
                return ResourceManager.GetString("EditVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Error adding reading.
        /// </summary>
        public static string ErrorAddingReading {
            get {
                return ResourceManager.GetString("ErrorAddingReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Error loading ownership.
        /// </summary>
        public static string ErrorLoadingOwnership {
            get {
                return ResourceManager.GetString("ErrorLoadingOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Error loading reading.
        /// </summary>
        public static string ErrorLoadingReading {
            get {
                return ResourceManager.GetString("ErrorLoadingReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ErrorUploadingImage.
        /// </summary>
        public static string ErrorUploadingImage {
            get {
                return ResourceManager.GetString("ErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to {count} days.
        /// </summary>
        public static string FewDays {
            get {
                return ResourceManager.GetString("FewDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to FieldsCanBeOverwritten.
        /// </summary>
        public static string FieldsCanBeOverwritten {
            get {
                return ResourceManager.GetString("FieldsCanBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to HidePreviews.
        /// </summary>
        public static string HidePreviews {
            get {
                return ResourceManager.GetString("HidePreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string Identifiers {
            get {
                return ResourceManager.GetString("Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ImageDimensions.
        /// </summary>
        public static string ImageDimensions {
            get {
                return ResourceManager.GetString("ImageDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ImageUploadedSuccessfully.
        /// </summary>
        public static string ImageUploadedSuccessfully {
            get {
                return ResourceManager.GetString("ImageUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to InvalidCropBoundaries.
        /// </summary>
        public static string InvalidCropBoundaries {
            get {
                return ResourceManager.GetString("InvalidCropBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to IsDeleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Preorder.
        /// </summary>
        public static string ItsPreorder {
            get {
                return ResourceManager.GetString("ItsPreorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Login here.
        /// </summary>
        public static string LoginHere {
            get {
                return ResourceManager.GetString("LoginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Login with your account.
        /// </summary>
        public static string LoginWithYourAccount {
            get {
                return ResourceManager.GetString("LoginWithYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Manga Shelf.
        /// </summary>
        public static string MangaShelf {
            get {
                return ResourceManager.GetString("MangaShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ManualCrop.
        /// </summary>
        public static string ManualCrop {
            get {
                return ResourceManager.GetString("ManualCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ManualCropControls.
        /// </summary>
        public static string ManualCropControls {
            get {
                return ResourceManager.GetString("ManualCropControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to My manga.
        /// </summary>
        public static string MyShelf {
            get {
                return ResourceManager.GetString("MyShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to NewManga.
        /// </summary>
        public static string NewManga {
            get {
                return ResourceManager.GetString("NewManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to NewPreorders.
        /// </summary>
        public static string NewPreorders {
            get {
                return ResourceManager.GetString("NewPreorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to No updates found for the selected date range..
        /// </summary>
        public static string No_updates_found_for_the_selected_date_range_ {
            get {
                return ResourceManager.GetString("No updates found for the selected date range.", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to No description.
        /// </summary>
        public static string NoDescrption {
            get {
                return ResourceManager.GetString("NoDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to No news.
        /// </summary>
        public static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to No preorders.
        /// </summary>
        public static string NoPreorders {
            get {
                return ResourceManager.GetString("NoPreorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to NoReviews.
        /// </summary>
        public static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to NothingSelected.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to {count} day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Order by.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to OriginalCover.
        /// </summary>
        public static string OriginalCover {
            get {
                return ResourceManager.GetString("OriginalCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Own.
        /// </summary>
        public static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Popularity.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Preorder.
        /// </summary>
        public static string Preorder {
            get {
                return ResourceManager.GetString("Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Preorder arrived.
        /// </summary>
        public static string PreorderArrived {
            get {
                return ResourceManager.GetString("PreorderArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Preorder date.
        /// </summary>
        public static string PreorderDate {
            get {
                return ResourceManager.GetString("PreorderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Late.
        /// </summary>
        public static string PreorderIsDue {
            get {
                return ResourceManager.GetString("PreorderIsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Preorders.
        /// </summary>
        public static string Preorders {
            get {
                return ResourceManager.GetString("Preorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to PreorderStart.
        /// </summary>
        public static string PreorderStart {
            get {
                return ResourceManager.GetString("PreorderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Publish.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Publishing.
        /// </summary>
        public static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to PurchaseUrl.
        /// </summary>
        public static string PurchaseUrl {
            get {
                return ResourceManager.GetString("PurchaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Register here.
        /// </summary>
        public static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Released.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ResetBoundaries.
        /// </summary>
        public static string ResetBoundaries {
            get {
                return ResourceManager.GetString("ResetBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Results per page.
        /// </summary>
        public static string ResultPerPage {
            get {
                return ResourceManager.GetString("ResultPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SaveChanges.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SelectedFile.
        /// </summary>
        public static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesAuthors.
        /// </summary>
        public static string SeriesAuthors {
            get {
                return ResourceManager.GetString("SeriesAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesDetails.
        /// </summary>
        public static string SeriesDetails {
            get {
                return ResourceManager.GetString("SeriesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesId.
        /// </summary>
        public static string SeriesId {
            get {
                return ResourceManager.GetString("SeriesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesOriginalTitle.
        /// </summary>
        public static string SeriesOriginalTitle {
            get {
                return ResourceManager.GetString("SeriesOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesPublicId.
        /// </summary>
        public static string SeriesPublicId {
            get {
                return ResourceManager.GetString("SeriesPublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesStatus.
        /// </summary>
        public static string SeriesStatus {
            get {
                return ResourceManager.GetString("SeriesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Series title.
        /// </summary>
        public static string SeriesTitle {
            get {
                return ResourceManager.GetString("SeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesTotalVolumes.
        /// </summary>
        public static string SeriesTotalVolumes {
            get {
                return ResourceManager.GetString("SeriesTotalVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SeriesType.
        /// </summary>
        public static string SeriesType {
            get {
                return ResourceManager.GetString("SeriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ShowPreviewOverlay.
        /// </summary>
        public static string ShowPreviewOverlay {
            get {
                return ResourceManager.GetString("ShowPreviewOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SingleIssue.
        /// </summary>
        public static string SingleIssue {
            get {
                return ResourceManager.GetString("SingleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to SmallCover.
        /// </summary>
        public static string SmallCover {
            get {
                return ResourceManager.GetString("SmallCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to ThisIsPreorderVolume.
        /// </summary>
        public static string ThisIsPreorderVolume {
            get {
                return ResourceManager.GetString("ThisIsPreorderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to UploadVolumeImage.
        /// </summary>
        public static string UploadVolumeImage {
            get {
                return ResourceManager.GetString("UploadVolumeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeDetails.
        /// </summary>
        public static string VolumeDetails {
            get {
                return ResourceManager.GetString("VolumeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeId.
        /// </summary>
        public static string VolumeId {
            get {
                return ResourceManager.GetString("VolumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeIsbn.
        /// </summary>
        public static string VolumeIsbn {
            get {
                return ResourceManager.GetString("VolumeIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeNotFound.
        /// </summary>
        public static string VolumeNotFound {
            get {
                return ResourceManager.GetString("VolumeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeNumber.
        /// </summary>
        public static string VolumeNumber {
            get {
                return ResourceManager.GetString("VolumeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumePublicId.
        /// </summary>
        public static string VolumePublicId {
            get {
                return ResourceManager.GetString("VolumePublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeTitle.
        /// </summary>
        public static string VolumeTitle {
            get {
                return ResourceManager.GetString("VolumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to VolumeType.
        /// </summary>
        public static string VolumeType {
            get {
                return ResourceManager.GetString("VolumeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
