//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaShelf.Localization.Resources.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VolumePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VolumePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaShelf.Localization.Resources.Components.VolumePageResource", typeof(VolumePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOwnership.
        /// </summary>
        public static string AddOwnership {
            get {
                return ResourceManager.GetString("AddOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddReading.
        /// </summary>
        public static string AddReading {
            get {
                return ResourceManager.GetString("AddReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Wishlist.
        /// </summary>
        public static string AddToWishlist {
            get {
                return ResourceManager.GetString("AddToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Rating.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Restriction.
        /// </summary>
        public static string AgeRestriction {
            get {
                return ResourceManager.GetString("AgeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Crop.
        /// </summary>
        public static string ApplyCrop {
            get {
                return ResourceManager.GetString("ApplyCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Crop.
        /// </summary>
        public static string AutoCrop {
            get {
                return ResourceManager.GetString("AutoCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        public static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Volume Status.
        /// </summary>
        public static string ChangeVolumeStatus {
            get {
                return ResourceManager.GetString("ChangeVolumeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delivery.
        /// </summary>
        public static string ConfirmDelivery {
            get {
                return ResourceManager.GetString("ConfirmDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Image.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped Cover.
        /// </summary>
        public static string CroppedCover {
            get {
                return ResourceManager.GetString("CroppedCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped Preview.
        /// </summary>
        public static string CroppedPreview {
            get {
                return ResourceManager.GetString("CroppedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Size.
        /// </summary>
        public static string CropSize {
            get {
                return ResourceManager.GetString("CropSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop successful.
        /// </summary>
        public static string CropSuccessful {
            get {
                return ResourceManager.GetString("CropSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped Version.
        /// </summary>
        public static string CurrentCroppedVersion {
            get {
                return ResourceManager.GetString("CurrentCroppedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Digital {
            get {
                return ResourceManager.GetString("Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped.
        /// </summary>
        public static string Dropped {
            get {
                return ResourceManager.GetString("Dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditOwnership.
        /// </summary>
        public static string EditOwnership {
            get {
                return ResourceManager.GetString("EditOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditReading.
        /// </summary>
        public static string EditReading {
            get {
                return ResourceManager.GetString("EditReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Volume.
        /// </summary>
        public static string EditVolume {
            get {
                return ResourceManager.GetString("EditVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading image.
        /// </summary>
        public static string ErrorUploadingImage {
            get {
                return ResourceManager.GetString("ErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields can be overwritten by parser.
        /// </summary>
        public static string FieldsCanBeOverwritten {
            get {
                return ResourceManager.GetString("FieldsCanBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone.
        /// </summary>
        public static string Gone {
            get {
                return ResourceManager.GetString("Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Website.
        /// </summary>
        public static string GoToWebsite {
            get {
                return ResourceManager.GetString("GoToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiatus.
        /// </summary>
        public static string Hiatus {
            get {
                return ResourceManager.GetString("Hiatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Previews.
        /// </summary>
        public static string HidePreviews {
            get {
                return ResourceManager.GetString("HidePreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string Identifiers {
            get {
                return ResourceManager.GetString("Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Dimensions.
        /// </summary>
        public static string ImageDimensions {
            get {
                return ResourceManager.GetString("ImageDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploaded successfully.
        /// </summary>
        public static string ImageUploadedSuccessfully {
            get {
                return ResourceManager.GetString("ImageUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Library.
        /// </summary>
        public static string InLibrary {
            get {
                return ResourceManager.GetString("InLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid crop boundaries.
        /// </summary>
        public static string InvalidCropBoundaries {
            get {
                return ResourceManager.GetString("InvalidCropBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Menu.
        /// </summary>
        public static string LibraryMenu {
            get {
                return ResourceManager.GetString("LibraryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string Liked {
            get {
                return ResourceManager.GetString("Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to see your data.
        /// </summary>
        public static string LoginToSeeData {
            get {
                return ResourceManager.GetString("LoginToSeeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Crop.
        /// </summary>
        public static string ManualCrop {
            get {
                return ResourceManager.GetString("ManualCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Crop Controls.
        /// </summary>
        public static string ManualCropControls {
            get {
                return ResourceManager.GetString("ManualCropControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More in Series.
        /// </summary>
        public static string MoreInSeries {
            get {
                return ResourceManager.GetString("MoreInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        public static string NoDescrption {
            get {
                return ResourceManager.GetString("NoDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews yet.
        /// </summary>
        public static string NoReviews {
            get {
                return ResourceManager.GetString("NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Shot.
        /// </summary>
        public static string OneShot {
            get {
                return ResourceManager.GetString("OneShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hold.
        /// </summary>
        public static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Cover.
        /// </summary>
        public static string OriginalCover {
            get {
                return ResourceManager.GetString("OriginalCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Preview.
        /// </summary>
        public static string OriginalPreview {
            get {
                return ResourceManager.GetString("OriginalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        public static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnershipData.
        /// </summary>
        public static string OwnershipData {
            get {
                return ResourceManager.GetString("OwnershipData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        public static string Physical {
            get {
                return ResourceManager.GetString("Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan to Read.
        /// </summary>
        public static string PlanToRead {
            get {
                return ResourceManager.GetString("PlanToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder.
        /// </summary>
        public static string Preorder {
            get {
                return ResourceManager.GetString("Preorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preordered.
        /// </summary>
        public static string Preordered {
            get {
                return ResourceManager.GetString("Preordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder Start.
        /// </summary>
        public static string PreorderStart {
            get {
                return ResourceManager.GetString("PreorderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorder Started.
        /// </summary>
        public static string PreorderStarted {
            get {
                return ResourceManager.GetString("PreorderStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preorders started for {title} on {date}..
        /// </summary>
        public static string PreorderStartedMessage {
            get {
                return ResourceManager.GetString("PreorderStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing.
        /// </summary>
        public static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase URL.
        /// </summary>
        public static string PurchaseUrl {
            get {
                return ResourceManager.GetString("PurchaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Data.
        /// </summary>
        public static string ReaderData {
            get {
                return ResourceManager.GetString("ReaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Menu.
        /// </summary>
        public static string ReadingMenu {
            get {
                return ResourceManager.GetString("ReadingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readings.
        /// </summary>
        public static string Readings {
            get {
                return ResourceManager.GetString("Readings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date for {title} changed from {old} to {new}..
        /// </summary>
        public static string ReleaseDateChangedMessage {
            get {
                return ResourceManager.GetString("ReleaseDateChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Wishlist.
        /// </summary>
        public static string RemoveFromWishlist {
            get {
                return ResourceManager.GetString("RemoveFromWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Boundaries.
        /// </summary>
        public static string ResetBoundaries {
            get {
                return ResourceManager.GetString("ResetBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file.
        /// </summary>
        public static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string SeriesAuthors {
            get {
                return ResourceManager.GetString("SeriesAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Details.
        /// </summary>
        public static string SeriesDetails {
            get {
                return ResourceManager.GetString("SeriesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series ID.
        /// </summary>
        public static string SeriesId {
            get {
                return ResourceManager.GetString("SeriesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        public static string SeriesOriginalTitle {
            get {
                return ResourceManager.GetString("SeriesOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Public ID.
        /// </summary>
        public static string SeriesPublicId {
            get {
                return ResourceManager.GetString("SeriesPublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SeriesStatus {
            get {
                return ResourceManager.GetString("SeriesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Volumes.
        /// </summary>
        public static string SeriesTotalVolumes {
            get {
                return ResourceManager.GetString("SeriesTotalVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SeriesType {
            get {
                return ResourceManager.GetString("SeriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Gone.
        /// </summary>
        public static string SetGone {
            get {
                return ResourceManager.GetString("SetGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetHistoricStatus.
        /// </summary>
        public static string SetHistoricStatus {
            get {
                return ResourceManager.GetString("SetHistoricStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Library.
        /// </summary>
        public static string SetOwn {
            get {
                return ResourceManager.GetString("SetOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Preorder.
        /// </summary>
        public static string SetPreorder {
            get {
                return ResourceManager.GetString("SetPreorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowLess.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMore.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Preview Overlay.
        /// </summary>
        public static string ShowPreviewOverlay {
            get {
                return ResourceManager.GetString("ShowPreviewOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Previews.
        /// </summary>
        public static string ShowPreviews {
            get {
                return ResourceManager.GetString("ShowPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Issue.
        /// </summary>
        public static string SingleIssue {
            get {
                return ResourceManager.GetString("SingleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Cover.
        /// </summary>
        public static string SmallCover {
            get {
                return ResourceManager.GetString("SmallCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a preorder volume. Expected release date:.
        /// </summary>
        public static string ThisIsPreorderVolume {
            get {
                return ResourceManager.GetString("ThisIsPreorderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Volumes.
        /// </summary>
        public static string TotalVolumes {
            get {
                return ResourceManager.GetString("TotalVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string Unknown_Value {
            get {
                return ResourceManager.GetString("Unknown Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Volume Image.
        /// </summary>
        public static string UploadVolumeImage {
            get {
                return ResourceManager.GetString("UploadVolumeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Details.
        /// </summary>
        public static string VolumeDetails {
            get {
                return ResourceManager.GetString("VolumeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume ID.
        /// </summary>
        public static string VolumeId {
            get {
                return ResourceManager.GetString("VolumeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string VolumeIsbn {
            get {
                return ResourceManager.GetString("VolumeIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume not found.
        /// </summary>
        public static string VolumeNotFound {
            get {
                return ResourceManager.GetString("VolumeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Number.
        /// </summary>
        public static string VolumeNumber {
            get {
                return ResourceManager.GetString("VolumeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Public ID.
        /// </summary>
        public static string VolumePublicId {
            get {
                return ResourceManager.GetString("VolumePublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} was released on {date}..
        /// </summary>
        public static string VolumeReleasedMessage {
            get {
                return ResourceManager.GetString("VolumeReleasedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string VolumeTitle {
            get {
                return ResourceManager.GetString("VolumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Type.
        /// </summary>
        public static string VolumeType {
            get {
                return ResourceManager.GetString("VolumeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} was updated on {date}..
        /// </summary>
        public static string VolumeUpdatedMessage {
            get {
                return ResourceManager.GetString("VolumeUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlisted.
        /// </summary>
        public static string Wishlisted {
            get {
                return ResourceManager.GetString("Wishlisted", resourceCulture);
            }
        }
    }
}
