// <auto-generated />
using System;
using MangaShelf.DAL.System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaShelf.DAL.System.Migrations
{
    [DbContext(typeof(MangaSystemDbContext))]
    [Migration("20260224195805_removeAuditableFields")]
    partial class removeAuditableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MangaShelf.DAL.System.Models.Parser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("NextRun")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParserName")
                        .IsUnique();

                    b.ToTable("Parsers");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.ParserError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ParserRunId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("RunTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("VolumeJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParserRunId");

                    b.ToTable("ParserError");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.ParserJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("Finished")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ParserStatusId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Progress")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("VolumesAdded")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VolumesFound")
                        .HasColumnType("int");

                    b.Property<string>("VolumesUpdated")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParserStatusId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.ParserError", b =>
                {
                    b.HasOne("MangaShelf.DAL.System.Models.ParserJob", "ParserRun")
                        .WithMany("Errors")
                        .HasForeignKey("ParserRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParserRun");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.ParserJob", b =>
                {
                    b.HasOne("MangaShelf.DAL.System.Models.Parser", "ParserStatus")
                        .WithMany("Jobs")
                        .HasForeignKey("ParserStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParserStatus");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.Parser", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("MangaShelf.DAL.System.Models.ParserJob", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
